const p_chars = [['King Henry the Eighth', 'Henry VIII'],
 ['Duke of Norfolk', 'Henry VIII'],
 ['Duke of Suffolk', 'Henry VIII'],
 ['Cardinal Wolsey', 'Henry VIII'],
 ['Secretaries to Wolsey', 'Henry VIII'],
 ['Cromwell', 'Henry VIII'],
 ['Cardinal Campeius', 'Henry VIII'],
 ['Gardiner', 'Henry VIII'],
 ['Page to Gardiner', 'Henry VIII'],
 ['Queen Katherine', 'Henry VIII'],
 ['Griffith', 'Henry VIII'],
 ['Patience', 'Henry VIII'],
 ["Queen's Gentleman Usher", 'Henry VIII'],
 ['Capuchius', 'Henry VIII'],
 ['Duke of Buckingham', 'Henry VIII'],
 ['Lord Abergavenny', 'Henry VIII'],
 ['Earl of Surrey', 'Henry VIII'],
 ['Sir Nicholas Vaux', 'Henry VIII'],
 ['Knevet, former Surveyor to Buckingham', 'Henry VIII'],
 ['Brandon', 'Henry VIII'],
 ['Sergeant at Arms', 'Henry VIII'],
 ['First Gentleman', 'Henry VIII'],
 ['Second Gentleman', 'Henry VIII'],
 ['Anne Bullen', 'Henry VIII'],
 ['Old Lady', 'Henry VIII'],
 ['Lord Chamberlain', 'Henry VIII'],
 ['Lord Sands [also Sir Walter Sands]', 'Henry VIII'],
 ['Sir Thomas Lovell', 'Henry VIII'],
 ['Sir Henry Guilford', 'Henry VIII'],
 ['Bishop of Lincoln', 'Henry VIII'],
 ['Cranmer', 'Henry VIII'],
 ['Lord Chancellor', 'Henry VIII'],
 ['Garter King of Arms', 'Henry VIII'],
 ['Third Gentleman', 'Henry VIII'],
 ['Sir Anthony Denny', 'Henry VIII'],
 ['Doctor Butts', 'Henry VIII'],
 ['Keeper', 'Henry VIII'],
 ['Scribes', 'Henry VIII'],
 ['Crier', 'Henry VIII'],
 ['Prologue', 'Henry VIII'],
 ['Epilogue', 'Henry VIII'],
 ['King Henry IV', 'Henry IV, Part I'],
 ['Prince Hal', 'Henry IV, Part I'],
 ['Lord John of Lancaster', 'Henry IV, Part I'],
 ['Earl of Westmoreland', 'Henry IV, Part I'],
 ['Sir Walter Blunt', 'Henry IV, Part I'],
 ['Hotspur', 'Henry IV, Part I'],
 ['Lady Percy', 'Henry IV, Part I'],
 ['Earl of Northumberland', 'Henry IV, Part I'],
 ['Earl of Worcester', 'Henry IV, Part I'],
 ['Edmund Mortimer', 'Henry IV, Part I'],
 ['Lady Mortimer', 'Henry IV, Part I'],
 ['Owen Glendower', 'Henry IV, Part I'],
 ['Douglas', 'Henry IV, Part I'],
 ['Archbishop', 'Henry IV, Part I'],
 ['Sir Michael', 'Henry IV, Part I'],
 ['Sir Richard Vernon', 'Henry IV, Part I'],
 ['Sir John Falstaff', 'Henry IV, Part I'],
 ['Poins', 'Henry IV, Part I'],
 ['Bardolph', 'Henry IV, Part I'],
 ['Peto', 'Henry IV, Part I'],
 ['Gadshill', 'Henry IV, Part I'],
 ['Hostess', 'Henry IV, Part I'],
 ['Vintner', 'Henry IV, Part I'],
 ['Francis', 'Henry IV, Part I'],
 ['Rumor', 'Henry IV, Part II'],
 ['King Henry IV', 'Henry IV, Part II'],
 ['Prince Hal', 'Henry IV, Part II'],
 ['King Henry V', 'Henry IV, Part II'],
 ['John of Lancaster', 'Henry IV, Part II'],
 ['Thomas of Clarence', 'Henry IV, Part II'],
 ['Humphrey of Gloucester', 'Henry IV, Part II'],
 ['Earl of Northumberland', 'Henry IV, Part II'],
 ["Northumberland's wife", 'Henry IV, Part II'],
 ['Lady Percy', 'Henry IV, Part II'],
 ['Archbishop', 'Henry IV, Part II'],
 ['Lord Mowbray', 'Henry IV, Part II'],
 ['Lord Hastings', 'Henry IV, Part II'],
 ['Lord Bardolph', 'Henry IV, Part II'],
 ['Travers', 'Henry IV, Part II'],
 ['Morton', 'Henry IV, Part II'],
 ['Sir John Colevile', 'Henry IV, Part II'],
 ['Earl of Westmoreland', 'Henry IV, Part II'],
 ['Earl of Warwick', 'Henry IV, Part II'],
 ['Earl of Surrey', 'Henry IV, Part II'],
 ['Sir John Blunt', 'Henry IV, Part II'],
 ['Gower', 'Henry IV, Part II'],
 ['Harcourt', 'Henry IV, Part II'],
 ['Lord Chief Justice', 'Henry IV, Part II'],
 ['Sir John Falstaff', 'Henry IV, Part II'],
 ['Poins', 'Henry IV, Part II'],
 ['Bardolph', 'Henry IV, Part II'],
 ['Peto', 'Henry IV, Part II'],
 ['Pistol', 'Henry IV, Part II'],
 ["Falstaff's Page", 'Henry IV, Part II'],
 ['Hostess', 'Henry IV, Part II'],
 ['Doll Tearsheet', 'Henry IV, Part II'],
 ['Justice Robert Shallow', 'Henry IV, Part II'],
 ['Justice Silence', 'Henry IV, Part II'],
 ['Davy', 'Henry IV, Part II'],
 ['Mouldy', 'Henry IV, Part II'],
 ['Shadow', 'Henry IV, Part II'],
 ['Wart', 'Henry IV, Part II'],
 ['Feeble', 'Henry IV, Part II'],
 ['Bullcalf', 'Henry IV, Part II'],
 ['Fang', 'Henry IV, Part II'],
 ['Snare', 'Henry IV, Part II'],
 ['Epilogue', 'Henry IV, Part II'],
 ['Chorus', 'Henry V'],
 ['Henry V, King of England', 'Henry V'],
 ['Thomas, Duke of Exeter', 'Henry V'],
 ['Humphrey, Duke of Gloucester', 'Henry V'],
 ['John, Duke of Bedford', 'Henry V'],
 ['Thomas, Duke of Clarence', 'Henry V'],
 ['Duke of York', 'Henry V'],
 ['Earl of Westmoreland', 'Henry V'],
 ['Earl of Cambridge', 'Henry V'],
 ['Earl of Warwick', 'Henry V'],
 ['Earl of Salisbury', 'Henry V'],
 ['Earl of Huntington', 'Henry V'],
 ['Lord Scroop of Masham', 'Henry V'],
 ['Sir Thomas Grey', 'Henry V'],
 ['Hostess Quickly', 'Henry V'],
 ['Pistol', 'Henry V'],
 ['Nym', 'Henry V'],
 ['Bardolph', 'Henry V'],
 ['Boy', 'Henry V'],
 ['Sir Thomas Erpingham', 'Henry V'],
 ['Captain Fluellen', 'Henry V'],
 ['Captain Gower', 'Henry V'],
 ['Captain MacMorris', 'Henry V'],
 ['Captain Jamy', 'Henry V'],
 ['John Bates', 'Henry V'],
 ['Alexander Court', 'Henry V'],
 ['Michael Williams', 'Henry V'],
 ['Bishop of Canterbury', 'Henry V'],
 ['Bishop of Ely', 'Henry V'],
 ['King of France', 'Henry V'],
 ['Queen Isabel of France', 'Henry V'],
 ['Katherine', 'Henry V'],
 ['Alice', 'Henry V'],
 ['Dauphin', 'Henry V'],
 ['Duke of Berri', 'Henry V'],
 ['Duke of Brittany', 'Henry V'],
 ['Duke of OrlÃ©ans', 'Henry V'],
 ['Duke of Bourbon', 'Henry V'],
 ['Duke of Burgundy', 'Henry V'],
 ['Constable of France', 'Henry V'],
 ['Lord GrandprÃ©', 'Henry V'],
 ['Lord Rambures', 'Henry V'],
 ['Lord Beaumont', 'Henry V'],
 ['Montjoy', 'Henry V'],
 ['Monsieur Le Fer', 'Henry V'],
 ['King Henry VI', 'Henry VI, Part 1'],
 ['Talbot', 'Henry VI, Part 1'],
 ['John Talbot', 'Henry VI, Part 1'],
 ['Gloucester', 'Henry VI, Part 1'],
 ['Bedford', 'Henry VI, Part 1'],
 ['Exeter', 'Henry VI, Part 1'],
 ['Winchester', 'Henry VI, Part 1'],
 ['Somerset', 'Henry VI, Part 1'],
 ['Plantagenet', 'Henry VI, Part 1'],
 ['York', 'Henry VI, Part 1'],
 ['Warwick', 'Henry VI, Part 1'],
 ['Salisbury', 'Henry VI, Part 1'],
 ['Suffolk', 'Henry VI, Part 1'],
 ['Mortimer', 'Henry VI, Part 1'],
 ['Glansdale', 'Henry VI, Part 1'],
 ['Gargrave', 'Henry VI, Part 1'],
 ['Fastolf', 'Henry VI, Part 1'],
 ['Lucy', 'Henry VI, Part 1'],
 ['Woodville', 'Henry VI, Part 1'],
 ['Vernon', 'Henry VI, Part 1'],
 ['Basset', 'Henry VI, Part 1'],
 ['Lawyer', 'Henry VI, Part 1'],
 ['Jailors', 'Henry VI, Part 1'],
 ['Legate', 'Henry VI, Part 1'],
 ['Mayor', 'Henry VI, Part 1'],
 ['Charles', 'Henry VI, Part 1'],
 ['Pucelle', 'Henry VI, Part 1'],
 ['Reignier', 'Henry VI, Part 1'],
 ['Margaret', 'Henry VI, Part 1'],
 ['Alanson', 'Henry VI, Part 1'],
 ['Orleance', 'Henry VI, Part 1'],
 ['Burgundy', 'Henry VI, Part 1'],
 ['General', 'Henry VI, Part 1'],
 ['Countess', 'Henry VI, Part 1'],
 ['Porter', 'Henry VI, Part 1'],
 ['Master Gunner', 'Henry VI, Part 1'],
 ['Boy', 'Henry VI, Part 1'],
 ['Sergeant', 'Henry VI, Part 1'],
 ['Shepherd', 'Henry VI, Part 1'],
 ['King Henry VI', 'Henry VI, Part 2'],
 ['Queen Margaret', 'Henry VI, Part 2'],
 ['Gloucester', 'Henry VI, Part 2'],
 ['Duchess', 'Henry VI, Part 2'],
 ['Cardinal', 'Henry VI, Part 2'],
 ['Somerset', 'Henry VI, Part 2'],
 ['Suffolk', 'Henry VI, Part 2'],
 ['Buckingham', 'Henry VI, Part 2'],
 ['Clifford', 'Henry VI, Part 2'],
 ['Young Clifford', 'Henry VI, Part 2'],
 ['York', 'Henry VI, Part 2'],
 ['Salisbury', 'Henry VI, Part 2'],
 ['Warwick', 'Henry VI, Part 2'],
 ['Edward', 'Henry VI, Part 2'],
 ['Richard', 'Henry VI, Part 2'],
 ['Cade', 'Henry VI, Part 2'],
 ['Bevis', 'Henry VI, Part 2'],
 ['Holland', 'Henry VI, Part 2'],
 ['Dick', 'Henry VI, Part 2'],
 ['Smith', 'Henry VI, Part 2'],
 ['Michael', 'Henry VI, Part 2'],
 ['George', 'Henry VI, Part 2'],
 ['Scales', 'Henry VI, Part 2'],
 ['Saye', 'Henry VI, Part 2'],
 ['Stafford', 'Henry VI, Part 2'],
 ['Brother', 'Henry VI, Part 2'],
 ['Hume', 'Henry VI, Part 2'],
 ['Southwell', 'Henry VI, Part 2'],
 ['Jourdain', 'Henry VI, Part 2'],
 ['Bolingbroke', 'Henry VI, Part 2'],
 ['Spirit', 'Henry VI, Part 2'],
 ['Stanley', 'Henry VI, Part 2'],
 ['Sheriff', 'Henry VI, Part 2'],
 ['Horner', 'Henry VI, Part 2'],
 ['Thump', 'Henry VI, Part 2'],
 ['Petitioners', 'Henry VI, Part 2'],
 ['Neighbors', 'Henry VI, Part 2'],
 ['Prentices', 'Henry VI, Part 2'],
 ['Man', 'Henry VI, Part 2'],
 ['Simpcox', 'Henry VI, Part 2'],
 ['Wife', 'Henry VI, Part 2'],
 ['Mayor', 'Henry VI, Part 2'],
 ['Beadle', 'Henry VI, Part 2'],
 ['Lieutenant', 'Henry VI, Part 2'],
 ['Master', 'Henry VI, Part 2'],
 ['Mate', 'Henry VI, Part 2'],
 ['Whitmore', 'Henry VI, Part 2'],
 ['Gentlemen', 'Henry VI, Part 2'],
 ['Messengers', 'Henry VI, Part 2'],
 ['Servants', 'Henry VI, Part 2'],
 ['Herald', 'Henry VI, Part 2'],
 ['Post', 'Henry VI, Part 2'],
 ['Murderers', 'Henry VI, Part 2'],
 ['Vaux', 'Henry VI, Part 2'],
 ['Clerk', 'Henry VI, Part 2'],
 ['Citizens', 'Henry VI, Part 2'],
 ['Iden', 'Henry VI, Part 2'],
 ['King Henry VI', 'Henry VI, Part 3'],
 ['Queen Margaret', 'Henry VI, Part 3'],
 ['Prince Edward', 'Henry VI, Part 3'],
 ['Clifford', 'Henry VI, Part 3'],
 ['Northumberland', 'Henry VI, Part 3'],
 ['Westmorland', 'Henry VI, Part 3'],
 ['Exeter', 'Henry VI, Part 3'],
 ['Oxford', 'Henry VI, Part 3'],
 ['Somerville', 'Henry VI, Part 3'],
 ['Warwick', 'Henry VI, Part 3'],
 ['Montague', 'Henry VI, Part 3'],
 ['Somerset', 'Henry VI, Part 3'],
 ['York', 'Henry VI, Part 3'],
 ['Edward', 'Henry VI, Part 3'],
 ['King Edward IV', 'Henry VI, Part 3'],
 ['George', 'Henry VI, Part 3'],
 ['Clarence', 'Henry VI, Part 3'],
 ['Richard', 'Henry VI, Part 3'],
 ['Gloucester', 'Henry VI, Part 3'],
 ['Rutland', 'Henry VI, Part 3'],
 ['Sir John', 'Henry VI, Part 3'],
 ['Lady Grey', 'Henry VI, Part 3'],
 ['Queen Elizabeth', 'Henry VI, Part 3'],
 ['Rivers', 'Henry VI, Part 3'],
 ['Norfolk', 'Henry VI, Part 3'],
 ['Pembroke', 'Henry VI, Part 3'],
 ['Stafford', 'Henry VI, Part 3'],
 ['Hastings', 'Henry VI, Part 3'],
 ['Stanley', 'Henry VI, Part 3'],
 ['Montgomery', 'Henry VI, Part 3'],
 ['King Lewis', 'Henry VI, Part 3'],
 ['Lady Bona', 'Henry VI, Part 3'],
 ['Tutor', 'Henry VI, Part 3'],
 ['Son', 'Henry VI, Part 3'],
 ['Father', 'Henry VI, Part 3'],
 ['First Gamekeeper', 'Henry VI, Part 3'],
 ['Second Gamekeeper', 'Henry VI, Part 3'],
 ['Nobleman', 'Henry VI, Part 3'],
 ['Post', 'Henry VI, Part 3'],
 ['First Watch', 'Henry VI, Part 3'],
 ['Second Watch', 'Henry VI, Part 3'],
 ['Third Watch', 'Henry VI, Part 3'],
 ['Huntsman', 'Henry VI, Part 3'],
 ['Lieutenant', 'Henry VI, Part 3'],
 ['First Messenger', 'Henry VI, Part 3'],
 ['Second Messenger', 'Henry VI, Part 3'],
 ['Messengers', 'Henry VI, Part 3'],
 ['Mayor', 'Henry VI, Part 3'],
 ['Soldier', 'Henry VI, Part 3'],
 ['John', 'King John'],
 ['Queen Eleanor', 'King John'],
 ['Blanche', 'King John'],
 ['Prince Henry', 'King John'],
 ['Constance', 'King John'],
 ['Arthur', 'King John'],
 ['King Philip II', 'King John'],
 ['Louis the Dauphin', 'King John'],
 ['Duke of Austria', 'King John'],
 ['Limoges', 'King John'],
 ['Chatillion', 'King John'],
 ['Count Melun', 'King John'],
 ['French Herald', 'King John'],
 ['Cardinal Pandulph', 'King John'],
 ['Lady Faulconbridge', 'King John'],
 ['Bastard', 'King John'],
 ['Philip Faulconbridge', 'King John'],
 ['Robert Faulconbridge', 'King John'],
 ['James Gurney', 'King John'],
 ['Hubert', 'King John'],
 ['Earl of Salisbury', 'King John'],
 ['Earl of Pembroke', 'King John'],
 ['Earl of Essex', 'King John'],
 ['Lord Bigot', 'King John'],
 ['Citizen', 'King John'],
 ['Peter', 'King John'],
 ['English Herald', 'King John'],
 ['Executioners', 'King John'],
 ['Messenger', 'King John'],
 ['Messenger', 'King John'],
 ['King Richard II', 'Richard II'],
 ['Bushy', 'Richard II'],
 ['Bagot', 'Richard II'],
 ['Green', 'Richard II'],
 ['Queen', 'Richard II'],
 ['Ladies-in-waiting', 'Richard II'],
 ['John of Gaunt', 'Richard II'],
 ['Henry Bolingbroke', 'Richard II'],
 ['Hereford', 'Richard II'],
 ['Duchess of Gloucester', 'Richard II'],
 ['Duke of York', 'Richard II'],
 ['Duchess of York', 'Richard II'],
 ['Duke of Aumerle', 'Richard II'],
 ['Servingmen', 'Richard II'],
 ['Mowbray', 'Richard II'],
 ['Lord Marshal', 'Richard II'],
 ['First Herald', 'Richard II'],
 ['Second Herald', 'Richard II'],
 ['Earl of Salisbury', 'Richard II'],
 ['Bishop of Carlisle', 'Richard II'],
 ['Sir Stephen Scroop', 'Richard II'],
 ['Lord Berkeley', 'Richard II'],
 ['Abbot of Westminster', 'Richard II'],
 ['Welsh Captain', 'Richard II'],
 ['Earl of Northumberland', 'Richard II'],
 ['Lord Ross', 'Richard II'],
 ['Lord Willoughby', 'Richard II'],
 ['Harry Percy', 'Richard II'],
 ['Lord Fitzwater', 'Richard II'],
 ['Duke of Surrey', 'Richard II'],
 ['Another Lord', 'Richard II'],
 ['Gardener', 'Richard II'],
 ['Groom', 'Richard II'],
 ['Keeper', 'Richard II'],
 ['Sir Pierce of Exton', 'Richard II'],
 ['Richard', 'Richard III'],
 ['Lady Anne', 'Richard III'],
 ['King Edward IV', 'Richard III'],
 ['Queen Elizabeth', 'Richard III'],
 ['Prince Edward', 'Richard III'],
 ['Richard, Duke of York', 'Richard III'],
 ['George, Duke of Clarence', 'Richard III'],
 ['Boy', 'Richard III'],
 ['Daughter', 'Richard III'],
 ['Duchess of York', 'Richard III'],
 ['Queen Margaret', 'Richard III'],
 ['Duke of Buckingham', 'Richard III'],
 ['William, Lord Hastings', 'Richard III'],
 ['Lord Stanley', 'Richard III'],
 ['Earl Rivers', 'Richard III'],
 ['Lord Grey', 'Richard III'],
 ['Marquess of Dorset', 'Richard III'],
 ['Sir Thomas Vaughan', 'Richard III'],
 ['Sir William Catesby', 'Richard III'],
 ['Sir Richard Ratcliffe', 'Richard III'],
 ['Lord Lovell', 'Richard III'],
 ['Duke of Norfolk', 'Richard III'],
 ['Earl of Surrey', 'Richard III'],
 ['Earl of Richmond', 'Richard III'],
 ['Earl of Oxford', 'Richard III'],
 ['Sir James Blunt', 'Richard III'],
 ['Sir Walter Herbert', 'Richard III'],
 ['Sir William Brandon', 'Richard III'],
 ['Sir Christopher', 'Richard III'],
 ['Archbishop', 'Richard III'],
 ['Cardinal', 'Richard III'],
 ['John Morton, Bishop of Ely', 'Richard III'],
 ['Sir Robert Brakenbury', 'Richard III'],
 ['James Tyrrel', 'Richard III'],
 ['Gentleman', 'Richard III'],
 ['Murderers', 'Richard III'],
 ['Keeper', 'Richard III'],
 ['Citizens', 'Richard III'],
 ['Lord Mayor', 'Richard III'],
 ['Pursuivant', 'Richard III'],
 ['Sir John', 'Richard III'],
 ['Scrivener', 'Richard III'],
 ['Page', 'Richard III'],
 ['Sheriff', 'Richard III'],
 ['Messengers', 'Richard III'],
 ['Ghosts', 'Richard III']]
